### ISSUE TITLE
segfaults on 9front

### ISSUE THREAD

**Issue by joe9** [ashinn/chibi-scheme#453]
Hello,

chibi-scheme does not start the interpreter or run a basic "hello world" program. It segfaults.

Details including the stack trace are at: http://okturing.com/src/2005/body

Just want to check if you have any suggestions on how to go about debugging it.

Thanks

```
:glenda@cirno:/mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme; mk
echo '#define sexp_default_module_path "'/sys/lib/chibi-scheme'"' > include/chibi/install.h
echo '#define sexp_so_extension ".no-such-file"' >> include/chibi/install.h
echo '#define sexp_platform "plan9"' >> include/chibi/install.h
echo '#define sexp_version "'`{cat VERSION}'"' >> include/chibi/install.h
echo '#define sexp_release_name "'`{cat RELEASE}'"' >> include/chibi/install.h
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 gc.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 sexp.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 bignum.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 opcodes.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 plan9.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 vm.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 simplify.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 eval.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 main.c
6l  -o 6.out gc.6 sexp.6 bignum.6 opcodes.6 plan9.6 vm.6 simplify.6 eval.6 main.6
:glenda@cirno:/mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme; ./6.out test.scm
6.out 5824: suicide: sys: trap: fault read addr=0x411fcfd0 pc=0x22a9f0
:glenda@cirno:/mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme; cat test.scm

;; Hello world in R7RS Scheme.

(import (scheme base)
        (scheme write))

(display "Hello, world!")
(newline)
:glenda@cirno:/mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme; acid 5824
/proc/5824/text:amd64 plan 9 executable
/sys/lib/acid/port
/sys/lib/acid/amd64
acid: lstk()
sexp_env_cell_loc(ctx=0x414940,key=0x411fcfd0,env=0x417c70,localp=0x7fff00000001,varenv=0x0)+0x94 /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/eval.c:111
	ls=0x23e
sexp_env_cell(env=0x417c70,key=0x411fcfd0,localp=0x1)+0x2e /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/eval.c:121
sexp_env_define(env=0x417c70,key=0x411fcfd0,ctx=0x414940,value=0x418100)+0x5e /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/eval.c:177
	res=0x43e
sexp_make_null_env_op(ctx=0x414940)+0x111 /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/eval.c:2177
	e=0x417c70
	__sexp_gc_preserver1=0x7ffffeffec58
	core=0x418100
	__sexp_gc_preserver2=0x7ffffeffec40
	i=0x2347fa00000008
sexp_make_primitive_env_op(ctx=0x414940,version=0xf)+0x123 /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/eval.c:2187
	e=0x43e
	__sexp_gc_preserver1=0x7ffffeffed00
	op=0x43e
	__sexp_gc_preserver2=0x7ffffeffece8
	sym=0x43e
	__sexp_gc_preserver3=0x7ffffeffecd0
	name=0x43e
	__sexp_gc_preserver4=0x7ffffeffecb8
	i=0x22c3c700000000
sexp_make_eval_context(ctx=0x0,size=0x0,max_size=0x0,env=0x0,stack=0x0)+0x38b /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/eval.c:520
	res=0x414940
	__sexp_gc_preserver1=0x0
do_init_context(ctx=0x7ffffeffee58,heap_size=0x0,heap_max_size=0x0,fold_case=0x0,env=0x7ffffeffee00)+0x33 /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/main.c:263
run_main(argc=0x2,argv=0x7ffffeffef88)+0x271 /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/main.c:539
	prefix=0x0
	suffix=0x0
	main_symbol=0x0
	main_module=0x0
	quit=0x0
	init_loaded=0x0
	mods_loaded=0x0
	fold_case=0x0
	nonblocking=0x0
	heap_size=0x0
	heap_max_size=0x0
	out=0x3e
	ctx=0x0
	tmp=0x43e
	__sexp_gc_preserver1=0x0
	sym=0x43e
	__sexp_gc_preserver2=0x0
	args=0x23e
	__sexp_gc_preserver3=0x0
	env=0x0
	__sexp_gc_preserver4=0x0
	arg=0x7ffffeffefa8
	i=0x1
	ls=0x0
	print=0x0
	c=0x0
	impmod=0x236889
	j=0x100000000
main(argc=0x2,argv=0x7ffffeffef88)+0x20 /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/main.c:651
_main+0x40 /sys/src/libc/amd64/main9.s:15
acid: 
```

**Comment by ashinn** [comment]
What does chibi-scheme -Q do?

**Comment by joe9** [comment]
Hello, 

Still crashing with a similar message

```
:glenda@cirno:/mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme; ./6.out -Q test.scm
6.out 6069: suicide: sys: trap: fault read addr=0x411fcfd0 pc=0x22a9f0
:glenda@cirno:/mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme; acid 6069
/proc/6069/text:amd64 plan 9 executable
/sys/lib/acid/port
/sys/lib/acid/amd64
acid: lstk()
sexp_env_cell_loc(ctx=0x414940,key=0x411fcfd0,env=0x417c70,localp=0x7fff00000001,varenv=0x0)+0x94 /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/eval.c:111
	ls=0x23e
sexp_env_cell(env=0x417c70,key=0x411fcfd0,localp=0x1)+0x2e /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/eval.c:121
sexp_env_define(env=0x417c70,key=0x411fcfd0,ctx=0x414940,value=0x418100)+0x5e /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/eval.c:177
	res=0x43e
sexp_make_null_env_op(ctx=0x414940)+0x111 /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/eval.c:2177
	e=0x417c70
	__sexp_gc_preserver1=0x7ffffeffec50
	core=0x418100
	__sexp_gc_preserver2=0x7ffffeffec38
	i=0x2347fa00000008
sexp_make_primitive_env_op(ctx=0x414940,version=0xf)+0x123 /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/eval.c:2187
	e=0x43e
	__sexp_gc_preserver1=0x7ffffeffecf8
	op=0x43e
	__sexp_gc_preserver2=0x7ffffeffece0
	sym=0x43e
	__sexp_gc_preserver3=0x7ffffeffecc8
	name=0x43e
	__sexp_gc_preserver4=0x7ffffeffecb0
	i=0x22c3c700000000
sexp_make_eval_context(ctx=0x0,size=0x0,max_size=0x0,env=0x0,stack=0x0)+0x38b /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/eval.c:520
	res=0x414940
	__sexp_gc_preserver1=0x0
do_init_context(ctx=0x7ffffeffee50,heap_size=0x0,heap_max_size=0x0,fold_case=0x0,env=0x7ffffeffedf8)+0x33 /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/main.c:263
run_main(argc=0x3,argv=0x7ffffeffef80)+0x16b5 /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/main.c:394
	prefix=0x0
	suffix=0x0
	main_symbol=0x0
	main_module=0x0
	quit=0x5100000000
	init_loaded=0x0
	mods_loaded=0x0
	fold_case=0x0
	nonblocking=0x0
	heap_size=0x0
	heap_max_size=0x0
	out=0x3e
	ctx=0x0
	tmp=0x43e
	__sexp_gc_preserver1=0x0
	sym=0x43e
	__sexp_gc_preserver2=0x0
	args=0x23e
	__sexp_gc_preserver3=0x0
	env=0x0
	__sexp_gc_preserver4=0x0
	arg=0x7ffffeffefa5
	i=0x1
	ls=0x0
	print=0x0
	c=0x51
	impmod=0x236889
	j=0x100000000
main(argc=0x3,argv=0x7ffffeffef80)+0x20 /mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/main.c:651
_main+0x40 /sys/src/libc/amd64/main9.s:15
acid: 
```

**Comment by nmeum** [comment]
I can still reproduce the segfault described by @joe9 with chibi 4edf3344f893c5c98fc20e3db034abc91e2c5092. However, I managed to find a workaround for this crash by changing the default configuration a bit and invoking `chibi-scheme` with the `-Q` option:

```
#define SEXP_USE_HUFF_SYMS 0

#define SEXP_USE_STRICT_TOPLEVEL_BINDINGS 0
#define SEXP_USE_RENAME_BINDINGS 0
```

After re-compiling with these options `./6.out -Q` seems to work as expected:

```
% ./6.out -Q
> (car '(1 2 3))
1
```

Without the `-Q` flag the following error is output with the configuration from above:

```
WARNING: exception inside undefined operator: #<SC 4541904 cond #f>
WARNING: exception inside undefined operator: #<SC 4542672 if #f>
WARNING: exception inside undefined operator: #<SC 4480304 begin #f>
WARNING: exception inside undefined operator: #<SC 4480928 if #f>
ERROR on line 218 of file ./lib/init-7.scm: undefined variable: else
```

I guess this is to be expected as the `cond` macro uses the `rename` S-expression and my configuration disables the use of rename bindings?

Unfortunately, without disabling rename bindings chibi segfaults when first accessing `sexp_env_renames` in the following `for`-loop:

https://github.com/ashinn/chibi-scheme/blob/181b7fe7e4d6b6685c99cb3811e0014b3f316ee6/eval.c#L85-L90

Backtrace just with `#define SEXP_USE_HUFF_SYMS 0` looks as follows:

```
acid: sexp_env_cell_loc1(varenv=0x0,localp=0x0,key=0x48c330)+0x20 /usr/soeren/src/chibi-scheme/eval.c:87
sexp_env_cell_loc(ctx=0x485c30,key=0x48c330,env=0x454770,localp=0x0,varenv=0x0)+0xd5 /usr/soeren/src/chibi-scheme/eval.c:117
	ls=0x3e
sexp_env_cell(env=0x43cd60,key=0x454860,localp=0x0)+0x2e /usr/soeren/src/chibi-scheme/eval.c:123
sexp_identifier_eq_op(ctx=0x485c30,e1=0x43cd60,id1=0x454860,e2=0x43cd60,id2=0x426990)+0x2a /usr/soeren/src/chibi-scheme/eval.c:658
	cell1=0x414b98
sexp_apply(proc=0x4dd3f0,args=0x454510,ctx=0x485c30)+0x1470 /usr/soeren/src/chibi-scheme/vm.c:1311
	stack=0x470e10
	self=0x454ac0
	__sexp_gc_preserver1=0x7fffffffdd90
	tmp1=0x454ac0
	__sexp_gc_preserver2=0x7fffffffdd78
	tmp2=0x11
	__sexp_gc_preserver3=0x7fffffffdd60
	top=0xe00000016
	fp=0xe
	cp=0x454aa0
	bc=0x45e820
	ip=0x45e8a5
	i=0x2
	j=0x200000000
	k=0x0
analyze(ctx=0x479130,object=0x426730,depth=0x6,defok=0x7fff00000000)+0x968 /usr/soeren/src/chibi-scheme/eval.c:1105
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffde78
	tmp=0x454510
	__sexp_gc_preserver2=0x7fffffffde60
	x=0x485c30
	__sexp_gc_preserver3=0x7fffffffde48
	cell=0x4dd4a0
	__sexp_gc_preserver4=0x7fffffffde30
	op=0x4dd410
analyze_list(x=0x43b070,ctx=0x479130,depth=0x5,defok=0x0)+0x155 /usr/soeren/src/chibi-scheme/eval.c:711
	res=0x4544b0
	__sexp_gc_preserver1=0x7fffffffdee8
	tmp=0x454490
	__sexp_gc_preserver2=0x7fffffffded0
analyze_app(x=0x445f10,depth=0x5)+0x23 /usr/soeren/src/chibi-scheme/eval.c:728
analyze(ctx=0x479130,object=0x445f10,depth=0x5,defok=0xffffffff)+0x518 /usr/soeren/src/chibi-scheme/eval.c:1055
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffdfd8
	tmp=0x43e
	__sexp_gc_preserver2=0x7fffffffdfc0
	x=0x445f10
	__sexp_gc_preserver3=0x7fffffffdfa8
	cell=0x0
	__sexp_gc_preserver4=0x7fffffffdf90
	op=0x4241b0
analyze_list(x=0x454250,ctx=0x479130,depth=0x4,defok=0xffffffff)+0x155 /usr/soeren/src/chibi-scheme/eval.c:711
	res=0x4543e0
	__sexp_gc_preserver1=0x7fffffffe048
	tmp=0x4543c0
	__sexp_gc_preserver2=0x7fffffffe030
analyze_app(x=0x454290,depth=0x4)+0x23 /usr/soeren/src/chibi-scheme/eval.c:728
analyze(ctx=0x479130,object=0x425a20,depth=0x4,defok=0x1)+0x518 /usr/soeren/src/chibi-scheme/eval.c:1055
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe138
	tmp=0x43ce10
	__sexp_gc_preserver2=0x7fffffffe120
	x=0x454290
	__sexp_gc_preserver3=0x7fffffffe108
	cell=0x0
	__sexp_gc_preserver4=0x7fffffffe0f0
	op=0x4dd410
analyze_seq(ls=0x43bc30,ctx=0x479130,depth=0x3,defok=0x1)+0xe1 /usr/soeren/src/chibi-scheme/eval.c:744
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe1a8
	tmp=0x43e
	__sexp_gc_preserver2=0x7fffffffe190
analyze_lambda(x=0x43cb60,ctx=0x473090,depth=0x3)+0x5b2 /usr/soeren/src/chibi-scheme/eval.c:839
	res=0x43cbc0
	__sexp_gc_preserver1=0x7fffffffe278
	body=0x43e
	__sexp_gc_preserver2=0x7fffffffe260
	tmp=0x43cd20
	__sexp_gc_preserver3=0x7fffffffe248
	value=0x43e
	__sexp_gc_preserver4=0x7fffffffe230
	defs=0x43e
	__sexp_gc_preserver5=0x7fffffffe218
	ctx2=0x479130
	__sexp_gc_preserver6=0x7fffffffe200
	verify_duplicates_p=0x1
	ls=0x425300
	trailing_non_procs=0x231a2400000000
	name=0x0
	ctx3=0x6
analyze_lambda(x=0x4234f0,ctx=0x46ad60,depth=0x3)+0xb50 /usr/soeren/src/chibi-scheme/eval.c:852
	res=0x43c710
	__sexp_gc_preserver1=0x7fffffffe368
	body=0x43c960
	__sexp_gc_preserver2=0x7fffffffe350
	tmp=0x43cb60
	__sexp_gc_preserver3=0x7fffffffe338
	value=0x43e
	__sexp_gc_preserver4=0x7fffffffe320
	defs=0x23e
	__sexp_gc_preserver5=0x7fffffffe308
	ctx2=0x473090
	__sexp_gc_preserver6=0x7fffffffe2f0
	verify_duplicates_p=0x1
	ls=0x43ca00
	trailing_non_procs=0x2337ff00000000
	name=0x4245d0
	ctx3=0x473090
analyze(ctx=0x46ad60,object=0x4234f0,depth=0x3,defok=0x0)+0xa85 /usr/soeren/src/chibi-scheme/eval.c:1071
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe428
	tmp=0x43e
	__sexp_gc_preserver2=0x7fffffffe410
	x=0x4234f0
	__sexp_gc_preserver3=0x7fffffffe3f8
	cell=0x41ed70
	__sexp_gc_preserver4=0x7fffffffe3e0
	op=0x20
analyze_list(x=0x43beb0,ctx=0x46ad60,depth=0x2,defok=0x0)+0x155 /usr/soeren/src/chibi-scheme/eval.c:711
	res=0x43c690
	__sexp_gc_preserver1=0x7fffffffe498
	tmp=0x43c670
	__sexp_gc_preserver2=0x7fffffffe480
analyze_app(x=0x423270,depth=0x2)+0x23 /usr/soeren/src/chibi-scheme/eval.c:728
analyze(ctx=0x46ad60,object=0x423270,depth=0x2,defok=0x0)+0x5cd /usr/soeren/src/chibi-scheme/eval.c:1127
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe588
	tmp=0x43e
	__sexp_gc_preserver2=0x7fffffffe570
	x=0x423270
	__sexp_gc_preserver3=0x7fffffffe558
	cell=0x462440
	__sexp_gc_preserver4=0x7fffffffe540
	op=0x47f6e0
analyze_list(x=0x43c300,ctx=0x46ad60,depth=0x1,defok=0x0)+0x155 /usr/soeren/src/chibi-scheme/eval.c:711
	res=0x43c630
	__sexp_gc_preserver1=0x7fffffffe5f8
	tmp=0x43c610
	__sexp_gc_preserver2=0x7fffffffe5e0
analyze_app(x=0x43c320,depth=0x1)+0x23 /usr/soeren/src/chibi-scheme/eval.c:728
analyze(ctx=0x46ad60,object=0x43c320,depth=0x7fff00000001,defok=0x7fff00000001)+0x5cd /usr/soeren/src/chibi-scheme/eval.c:1127
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe6e8
	tmp=0x43e
	__sexp_gc_preserver2=0x7fffffffe6d0
	x=0x43c320
	__sexp_gc_preserver3=0x7fffffffe6b8
	cell=0x41ba90
	__sexp_gc_preserver4=0x7fffffffe6a0
	op=0x42c750
sexp_analyze(x=0x43c320)+0x24 /usr/soeren/src/chibi-scheme/eval.c:1169
sexp_compile_op(env=0x41eb00,self=0x0,ctx=0x462cb0,obj=0x43c320,n=0x2)+0x16b /usr/soeren/src/chibi-scheme/eval.c:2607
	ast=0x43e
	__sexp_gc_preserver1=0x7fffffffe7b0
	tmp=0x0
	__sexp_gc_preserver2=0x7fffffffe798
	res=0x43e
	__sexp_gc_preserver3=0x7fffffffe780
	ctx2=0x46ad60
sexp_eval_op(env=0x41eb00,self=0x0,ctx=0x44e170,n=0x2,obj=0x43c320)+0x1ac /usr/soeren/src/chibi-scheme/eval.c:2640
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe838
	tmp=0x0
	__sexp_gc_preserver2=0x7fffffffe820
	params=0x23e
	__sexp_gc_preserver3=0x7fffffffe808
	top=0x2329be00000000
	ctx2=0x462cb0
analyze_bind_syntax(eval_ctx=0x44e170,ls=0x43c3d0,bind_ctx=0x44e170,localp=0x0)+0x4a8 /usr/soeren/src/chibi-scheme/eval.c:969
	res=0x43e
	mac=0x43e
	__sexp_gc_preserver1=0x7fffffffe8b8
	tmp=0x43e
	__sexp_gc_preserver2=0x7fffffffe8a0
	name=0x0
analyze_define_syntax(ctx=0x44e170,x=0x43c3b0)+0xb6 /usr/soeren/src/chibi-scheme/eval.c:1000
	tmp=0x43c3d0
	__sexp_gc_preserver1=0x7fffffffe920
analyze(ctx=0x44e170,object=0x422db0,depth=0x7fff00000001,defok=0x7fff00000001)+0xc76 /usr/soeren/src/chibi-scheme/eval.c:1089
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe9c8
	tmp=0x43c1b0
	__sexp_gc_preserver2=0x7fffffffe9b0
	x=0x43c3b0
	__sexp_gc_preserver3=0x7fffffffe998
	cell=0x41f170
	__sexp_gc_preserver4=0x7fffffffe980
	op=0x454b20
sexp_analyze(x=0x422db0)+0x24 /usr/soeren/src/chibi-scheme/eval.c:1169
sexp_compile_op(env=0x41eb00,self=0x0,ctx=0x4460c0,obj=0x422db0,n=0x2)+0x16b /usr/soeren/src/chibi-scheme/eval.c:2607
	ast=0x43e
	__sexp_gc_preserver1=0x7fffffffea90
	tmp=0x0
	__sexp_gc_preserver2=0x7fffffffea78
	res=0x43e
	__sexp_gc_preserver3=0x7fffffffea60
	ctx2=0x44e170
sexp_eval_op(env=0x41eb00,self=0x0,ctx=0x43d900,n=0x2,obj=0x422db0)+0x1ac /usr/soeren/src/chibi-scheme/eval.c:2640
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffeb18
	tmp=0x0
	__sexp_gc_preserver2=0x7fffffffeb00
	params=0x23e
	__sexp_gc_preserver3=0x7fffffffeae8
	top=0x23493800000000
	ctx2=0x4460c0
sexp_load_op(self=0x0,env=0x41eb00,source=0x43d890,ctx=0x414bd0)+0x32d /usr/soeren/src/chibi-scheme/eval.c:1457
	ctx2=0x43d900
	__sexp_gc_preserver1=0x7fffffffebe0
	x=0x422db0
	__sexp_gc_preserver2=0x7fffffffebc8
	in=0x43d8b0
	__sexp_gc_preserver3=0x7fffffffebb0
	res=0x43e
	__sexp_gc_preserver4=0x7fffffffeb98
	out=0x43e
	__sexp_gc_preserver5=0x7fffffffeb80
sexp_load_module_file(ctx=0x414bd0,file=0x7fffffffece4,env=0x41eb00)+0x10c /usr/soeren/src/chibi-scheme/eval.c:2299
	path=0x43d890
	__sexp_gc_preserver1=0x7fffffffec38
sexp_load_standard_env(e=0x41eb00,ctx=0x414bd0,version=0xf)+0x3d9 /usr/soeren/src/chibi-scheme/eval.c:2450
	op=0x43d770
	__sexp_gc_preserver1=0x7fffffffecd8
	tmp=0x43d820
	__sexp_gc_preserver2=0x7fffffffecc0
	sym=0x41f700
	__sexp_gc_preserver3=0x7fffffffeca8
	init_file=0x732e372d74696e69
	len=0x23b94900000005
sexp_load_standard_repl_env(ctx=0x414bd0,env=0x41eb00,k=0xf,bootp=0x0,nonblocking=0x0)+0x5f /usr/soeren/src/chibi-scheme/main.c:249
	e=0x43e
	__sexp_gc_preserver1=0x7fffffffedb0
run_main(argc=0x1,argv=0x7fffffffefa0)+0x5ad /usr/soeren/src/chibi-scheme/main.c:555
	prefix=0x0
	suffix=0x0
	main_symbol=0x0
	main_module=0x0
	quit=0x0
	init_loaded=0x0
	mods_loaded=0x0
	fold_case=0x0
	nonblocking=0x0
	heap_size=0x0
	heap_max_size=0x0
	out=0x3e
	ctx=0x414bd0
	tmp=0x43d5e0
	__sexp_gc_preserver1=0x7fffffffee60
	sym=0x43e
	__sexp_gc_preserver2=0x7fffffffee48
	args=0x43d600
	__sexp_gc_preserver3=0x7fffffffee30
	env=0x41eb00
	__sexp_gc_preserver4=0x7fffffffee18
	arg=0x7fffffffefb1
	i=0x1
	ls=0x0
	print=0x0
	c=0x0
	impmod=0x23a92f
	j=0x100000000
main(argc=0x1,argv=0x7fffffffefa0)+0x20 /usr/soeren/src/chibi-scheme/main.c:661
_main+0x40 /sys/src/libc/amd64/main9.s:15
```

Would be interested in getting this fixed, but I am not too familiar with neither 9front nor chibi-scheme internals. If anyone has an idea how this can be debugged further, let me know.

**Comment by nmeum** [comment]
One more clue: Contrary to Plan 9 (?), 9front actually supports 64 Bit architectures. Unfortunately, the pre-processor based check for 64 Bit architectures does not work correctly on 9front as it doesn't seem to set any of the consulted macros:

https://github.com/ashinn/chibi-scheme/blob/4335d238fb263531c154922b6d73a9705a6494fd/include/chibi/features.h#L310-L316

This code needs to be adjusted, this seems to fix the `sexp_pointer` macro on 9front which seems to be the root cause of the crashed described in https://github.com/ashinn/chibi-scheme/issues/453#issuecomment-751250673. Unfortunately, this doesn't seem to be the only remaining issue :/

**Comment by ashinn** [comment]
@nmeum, what preprocessor macro does the 9front compiler set for 64-bit?

-Q simply skips loading the standard env, so you have only core forms and primitives available.  If you get further along with that it may just be a memory corruption issue, e.g. due to assumptions Chibi makes about alignment that do not hold on 9front.

I think SEXP_USE_RENAME_BINDINGS is unlikely to be an issue either way, however _disabling_ it may have led to some corruption which I've fixed.

**Comment by nmeum** [comment]
> what preprocessor macro does the 9front compiler set for 64-bit?

Unfortunately, 9front does not set any preprocessor macro for this. It is, however, possible to determine the current architecture from the `$objtype` as defined in the `mkfile` and set `SEXP_64_BIT` from there:

```patch
diff -upr /home/soeren/src/chibi-scheme/include/chibi/bignum.h chibi-scheme/include/chibi/bignum.h
--- /home/soeren/src/chibi-scheme/include/chibi/bignum.h	2020-12-27 13:25:13.299738983 +0100
+++ chibi-scheme/include/chibi/bignum.h	2020-12-28 13:18:26.000000000 +0100
@@ -8,7 +8,11 @@
 #include "chibi/eval.h"
 
 #if SEXP_USE_CUSTOM_LONG_LONGS
+#ifndef PLAN9
+/* typedefs defined in sexp.h on Plan 9 */
 #include <stdint.h>
+#endif
+
 typedef struct
 {
   uint64_t hi;
diff -upr /home/soeren/src/chibi-scheme/mkfile chibi-scheme/mkfile
--- /home/soeren/src/chibi-scheme/mkfile	2020-12-27 13:25:13.389739464 +0100
+++ chibi-scheme/mkfile	2020-12-28 13:15:49.000000000 +0100
@@ -8,7 +8,7 @@ CHIBI=./$O.out
 GENSTATIC=./tools/chibi-genstatic
 
 CPPFLAGS= -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0
-CFLAGS= -p $CPPFLAGS
+CFLAGS= -p $CPPFLAGS `{if (~ $objtype amd64) echo -DSEXP_64_BIT}
 CFLAGS_STATIC=$CFLAGS -DSEXP_USE_STATIC_LIBS
 
 OFILES=gc.$O sexp.$O bignum.$O opcodes.$O plan9.$O vm.$O simplify.$O eval.$O main.$O $STATIC
```

A more "portable" solution might be to check for the size of `uintptr_t` in `features.h`? For example, `sizeof(uintptr_t) == 8`? As an alternative to explicitly checking for different architecture macros.

**Comment by nmeum** [comment]
With the patch from my previous comment and `#define SEXP_USE_HUFF_SYMS 0` chibi still crashes with:

```
% ./6.out
6.out 1075: suicide: sys: trap: fault read addr=0x0 pc=0x2366cf
```

Backtrace for this crash looks as follows:

```
acid: sexp_env_cell_loc1(varenv=0x0,localp=0x0,key=0x423780)+0x20 /usr/soeren/src/chibi-scheme/eval.c:86
sexp_env_cell_loc(ctx=0x46a340,key=0x423780,env=0x43efc0,localp=0x0,varenv=0x0)+0xd1 /usr/soeren/src/chibi-scheme/eval.c:117
	ls=0x3e
sexp_env_cell(env=0x43e7e0,key=0x43f1e0,localp=0x0)+0x2e /usr/soeren/src/chibi-scheme/eval.c:123
sexp_identifier_eq_op(ctx=0x46a340,e1=0x43e7e0,id1=0x43f1e0,e2=0x43e7e0,id2=0x582060)+0x2a /usr/soeren/src/chibi-scheme/eval.c:658
	cell1=0x0
sexp_apply(proc=0x564b80,args=0x43e9c0,ctx=0x46a340)+0x145f /usr/soeren/src/chibi-scheme/vm.c:1311
	stack=0x454db8
	self=0x43f4c0
	__sexp_gc_preserver1=0x7fffffffe138
	tmp1=0x43f4c0
	__sexp_gc_preserver2=0x7fffffffe120
	tmp2=0x11
	__sexp_gc_preserver3=0x7fffffffe108
	top=0xe00000016
	fp=0xe
	cp=0x43f480
	bc=0x496d20
	ip=0x496dad
	i=0x2
	j=0x200000000
	k=0x0
	prod=0x46a340
analyze(ctx=0x463240,object=0x581f20,depth=0x4,defok=0x1)+0x958 /usr/soeren/src/chibi-scheme/eval.c:1105
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe228
	tmp=0x43e9c0
	__sexp_gc_preserver2=0x7fffffffe210
	x=0x46a340
	__sexp_gc_preserver3=0x7fffffffe1f8
	cell=0x574f40
	__sexp_gc_preserver4=0x7fffffffe1e0
	op=0x564c80
analyze_seq(ls=0x5cc540,ctx=0x463240,depth=0x3,defok=0x1)+0xe1 /usr/soeren/src/chibi-scheme/eval.c:744
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe298
	tmp=0x43e
	__sexp_gc_preserver2=0x7fffffffe280
analyze_lambda(x=0x581740,ctx=0x45d1a0,depth=0x3)+0x5aa /usr/soeren/src/chibi-scheme/eval.c:839
	res=0x43e380
	__sexp_gc_preserver1=0x7fffffffe368
	body=0x43e
	__sexp_gc_preserver2=0x7fffffffe350
	tmp=0x43e460
	__sexp_gc_preserver3=0x7fffffffe338
	value=0x43e
	__sexp_gc_preserver4=0x7fffffffe320
	defs=0x43e
	__sexp_gc_preserver5=0x7fffffffe308
	ctx2=0x463240
	__sexp_gc_preserver6=0x7fffffffe2f0
	verify_duplicates_p=0x1
	ls=0x581b80
	trailing_non_procs=0x23bb4000000000
	name=0x0
	ctx3=0x41f620
analyze(ctx=0x45d1a0,object=0x581740,depth=0x3,defok=0x0)+0xa75 /usr/soeren/src/chibi-scheme/eval.c:1071
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe428
	tmp=0x43e
	__sexp_gc_preserver2=0x7fffffffe410
	x=0x581740
	__sexp_gc_preserver3=0x7fffffffe3f8
	cell=0x41f6a0
	__sexp_gc_preserver4=0x7fffffffe3e0
	op=0x40
analyze_list(x=0x5cc600,ctx=0x45d1a0,depth=0x2,defok=0x0)+0x153 /usr/soeren/src/chibi-scheme/eval.c:711
	res=0x43e280
	__sexp_gc_preserver1=0x7fffffffe498
	tmp=0x43e140
	__sexp_gc_preserver2=0x7fffffffe480
analyze_app(x=0x581640,depth=0x2)+0x23 /usr/soeren/src/chibi-scheme/eval.c:728
analyze(ctx=0x45d1a0,object=0x581640,depth=0x2,defok=0x0)+0x5c3 /usr/soeren/src/chibi-scheme/eval.c:1127
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe588
	tmp=0x43e
	__sexp_gc_preserver2=0x7fffffffe570
	x=0x581640
	__sexp_gc_preserver3=0x7fffffffe558
	cell=0x4d12c0
	__sexp_gc_preserver4=0x7fffffffe540
	op=0x4d2520
analyze_list(x=0x43dc00,ctx=0x45d1a0,depth=0x1,defok=0x0)+0x153 /usr/soeren/src/chibi-scheme/eval.c:711
	res=0x43e080
	__sexp_gc_preserver1=0x7fffffffe5f8
	tmp=0x43dfe0
	__sexp_gc_preserver2=0x7fffffffe5e0
analyze_app(x=0x43dc40,depth=0x1)+0x23 /usr/soeren/src/chibi-scheme/eval.c:728
analyze(ctx=0x45d1a0,object=0x43dc40,depth=0x7fff00000001,defok=0x7fff00000001)+0x5c3 /usr/soeren/src/chibi-scheme/eval.c:1127
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe6e8
	tmp=0x43e
	__sexp_gc_preserver2=0x7fffffffe6d0
	x=0x43dc40
	__sexp_gc_preserver3=0x7fffffffe6b8
	cell=0x441d20
	__sexp_gc_preserver4=0x7fffffffe6a0
	op=0x4694a0
sexp_analyze(x=0x43dc40)+0x24 /usr/soeren/src/chibi-scheme/eval.c:1169
sexp_compile_op(env=0x41f380,self=0x0,ctx=0x44cce0,obj=0x43dc40,n=0x2)+0x169 /usr/soeren/src/chibi-scheme/eval.c:2607
	ast=0x43e
	__sexp_gc_preserver1=0x7fffffffe7b0
	tmp=0x0
	__sexp_gc_preserver2=0x7fffffffe798
	res=0x43e
	__sexp_gc_preserver3=0x7fffffffe780
	ctx2=0x45d1a0
sexp_eval_op(env=0x41f380,self=0x0,ctx=0x609060,n=0x2,obj=0x43dc40)+0x1aa /usr/soeren/src/chibi-scheme/eval.c:2640
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe838
	tmp=0x0
	__sexp_gc_preserver2=0x7fffffffe820
	params=0x23e
	__sexp_gc_preserver3=0x7fffffffe808
	top=0x23ad1300000000
	ctx2=0x44cce0
analyze_bind_syntax(eval_ctx=0x609060,ls=0x43dde0,bind_ctx=0x609060,localp=0x0)+0x49d /usr/soeren/src/chibi-scheme/eval.c:969
	res=0x43e
	mac=0x43e
	__sexp_gc_preserver1=0x7fffffffe8b8
	tmp=0x43e
	__sexp_gc_preserver2=0x7fffffffe8a0
	name=0x0
analyze_define_syntax(ctx=0x609060,x=0x43dda0)+0xb5 /usr/soeren/src/chibi-scheme/eval.c:1000
	tmp=0x43dde0
	__sexp_gc_preserver1=0x7fffffffe920
analyze(ctx=0x609060,object=0x575180,depth=0x7fff00000001,defok=0x7fff00000001)+0xc65 /usr/soeren/src/chibi-scheme/eval.c:1089
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffe9c8
	tmp=0x5cea60
	__sexp_gc_preserver2=0x7fffffffe9b0
	x=0x43dda0
	__sexp_gc_preserver3=0x7fffffffe998
	cell=0x41fc20
	__sexp_gc_preserver4=0x7fffffffe980
	op=0x486e20
sexp_analyze(x=0x575180)+0x24 /usr/soeren/src/chibi-scheme/eval.c:1169
sexp_compile_op(env=0x41f380,self=0x0,ctx=0x5f9da0,obj=0x575180,n=0x2)+0x169 /usr/soeren/src/chibi-scheme/eval.c:2607
	ast=0x43e
	__sexp_gc_preserver1=0x7fffffffea90
	tmp=0x0
	__sexp_gc_preserver2=0x7fffffffea78
	res=0x43e
	__sexp_gc_preserver3=0x7fffffffea60
	ctx2=0x609060
sexp_eval_op(env=0x41f380,self=0x0,ctx=0x444540,n=0x2,obj=0x575180)+0x1aa /usr/soeren/src/chibi-scheme/eval.c:2640
	res=0x43e
	__sexp_gc_preserver1=0x7fffffffeb18
	tmp=0x0
	__sexp_gc_preserver2=0x7fffffffeb00
	params=0x23e
	__sexp_gc_preserver3=0x7fffffffeae8
	top=0x23cc5300000000
	ctx2=0x5f9da0
sexp_load_op(self=0x0,env=0x41f380,source=0x4444c0,ctx=0x414be0)+0x328 /usr/soeren/src/chibi-scheme/eval.c:1457
	ctx2=0x444540
	__sexp_gc_preserver1=0x7fffffffebe0
	x=0x575180
	__sexp_gc_preserver2=0x7fffffffebc8
	in=0x4444e0
	__sexp_gc_preserver3=0x7fffffffebb0
	res=0x43e
	__sexp_gc_preserver4=0x7fffffffeb98
	out=0x43e
	__sexp_gc_preserver5=0x7fffffffeb80
sexp_load_module_file(ctx=0x414be0,file=0x7fffffffece4,env=0x41f380)+0x10b /usr/soeren/src/chibi-scheme/eval.c:2299
	path=0x4444c0
	__sexp_gc_preserver1=0x7fffffffec38
sexp_load_standard_env(e=0x41f380,ctx=0x414be0,version=0xf)+0x3d9 /usr/soeren/src/chibi-scheme/eval.c:2450
	op=0x444320
	__sexp_gc_preserver1=0x7fffffffecd8
	tmp=0x444400
	__sexp_gc_preserver2=0x7fffffffecc0
	sym=0x420420
	__sexp_gc_preserver3=0x7fffffffeca8
	init_file=0x732e372d74696e69
	len=0x244aec00000005
sexp_load_standard_repl_env(ctx=0x414be0,env=0x41f380,k=0xf,bootp=0x0,nonblocking=0x0)+0x5f /usr/soeren/src/chibi-scheme/main.c:249
	e=0x43e
	__sexp_gc_preserver1=0x7fffffffedb0
run_main(argc=0x1,argv=0x7fffffffefa0)+0x5ad /usr/soeren/src/chibi-scheme/main.c:555
	prefix=0x0
	suffix=0x0
	main_symbol=0x0
	main_module=0x0
	quit=0x0
	init_loaded=0x0
	mods_loaded=0x0
	fold_case=0x0
	nonblocking=0x0
	heap_size=0x0
	heap_max_size=0x0
	out=0x3e
	ctx=0x414be0
	tmp=0x4440a0
	__sexp_gc_preserver1=0x7fffffffee60
	sym=0x43e
	__sexp_gc_preserver2=0x7fffffffee48
	args=0x4440c0
	__sexp_gc_preserver3=0x7fffffffee30
	env=0x41f380
	__sexp_gc_preserver4=0x7fffffffee18
	arg=0x7fffffffefb1
	i=0x1
	ls=0x0
	print=0x0
	c=0x0
	impmod=0x242bb9
	j=0x100000000
main(argc=0x1,argv=0x7fffffffefa0)+0x20 /usr/soeren/src/chibi-scheme/main.c:660
_main+0x40 /sys/src/libc/amd64/main9.s:15
```

I have really absolutely no idea how chibi works, but it seems to me that something which is not an `env` is passed to `sexp_env_cell_loc1` as the first function parameter (`env`), somehow causing a null pointer dereference? This diff prevents the null pointer deference, *but is of cause not a proper fix*:

```diff
--- /home/soeren/src/chibi-scheme/eval.c	2020-12-28 13:11:24.104853528 +0100
+++ eval.c	2020-12-28 13:31:50.000000000 +0100
@@ -109,8 +109,10 @@
     }
   cell = sexp_env_cell_loc1(env, key, localp, varenv);
   while (!cell && key && sexp_synclop(key)) {
-    if (!sexp_pairp(ls) && sexp_not(sexp_memq(ctx, sexp_synclo_expr(key), sexp_synclo_free_vars(key))))
-      env = sexp_synclo_env(key);
+    if (!sexp_pairp(ls) && sexp_not(sexp_memq(ctx, sexp_synclo_expr(key), sexp_synclo_free_vars(key)))) {
+      if (sexp_envp(sexp_synclo_env(key)))
+        env = sexp_synclo_env(key);
+    }
     key = sexp_synclo_expr(key);
     cell = sexp_env_cell_loc1(env, key, localp, varenv);
   }
```
